export const SET_FAVOURITE = "SET_FAVOURITE";
export const SET_NOT_FAVOURITE = "SET_NOT_FAVOURITE";
export const REMOVE_FAVOURITE = "REMOVE_FAVOURITE";
export const TO_FAVOURITES_VIEW = "TO_FAVOURITES_VIEW";
export const TO_MAIN_PAGE = "TO_MAIN_PAGE";
export const LOAD_IMAGES = "LOAD_IMAGES";
export const LOAD_FAVOURITE_IMAGES = "LOAD_FAVOURITE_IMAGES";
